### PR TITLE
Updated to work with latest markdown and python

### PR DESCRIPTION
**Pull request by JJK96**
Tested with Markdown 3.4.1 and python 3.10.5.

I'm not sure what priorities I should give when registering the extension, maybe that should be tweaked.
This worked for my usecases, so I decided to share it with the next visitor.

The tests do not completely work, so someone should have a look at what's going wrong there.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@JJK96 any chance to get tests passing? I'd love to merge this but i can't really do so without fixing the tests (i don't use it myself much anymore so i can't do that!)

**Comment by Migacz85** [comment]
What test are failing?

**Comment by JJK96** [comment]
```
============================= test session starts ==============================
platform darwin -- Python 3.10.8, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/nw/git/markdown2latex
collected 5 items

mdx_latex_test.py F.FFF                                                  [100%]

=================================== FAILURES ===================================
____________________________ TestMkdn2Latex.test_1 _____________________________

self = <mdx_latex_test.TestMkdn2Latex object at 0x102f19300>

    def test_1(self):
        ltx = mdx_latex.makeExtension()
        # or just mdx_latex.LaTeXExtension()
        ltx.extendMarkdown(self.md)
        # self.footnoteExtension.extendMarkdown(self.mdx_latexer)
        out = self.md.convert(self.mkdn_input)
        outlines = out.split('\n')
        explines = self.expected.split('\n')
        # TODO: this misses stuff if out > exp
        print('******** EXPECTED *********')
        print(self.expected)
        print('******** ACTUAL *********')
        print(out)
        print('******** ANALYSIS *********')
        for ii in range(len(explines)):
            if outlines[ii] != explines[ii]:
                print(ii)
                print('out:', '"%s"' % outlines[ii])
                print('exp:', '"%s"' % explines[ii])
        if len(explines) < len(outlines):
            print('Out longer than expected:')
            print(outlines[len(explines):])
        # for ii in range(len(out)):
        #    if out[ii] != self.expected[ii]:
        #        print out[ii:ii+10]
>       assert out == self.expected
E       AssertionError: assert '<root>\n\\ti...tim}\n</root>' == '\\title{Anna...end{verbatim}'
E         + <root>
E           \title{Anna Karenina}
E           
E           % ----------------------------------------------------------------
E           \maketitle
E           % ----------------------------------------------------------------
E           ...
E         
E         ...Full output truncated (114 lines hidden), use '-vv' to show

mdx_latex_test.py:176: AssertionError
----------------------------- Captured stdout call -----------------------------
******** EXPECTED *********
\title{Anna Karenina}

% ----------------------------------------------------------------
\maketitle
% ----------------------------------------------------------------


\section{A first section}

A simple list:

\begin{enumerate}
  \item Item 1
  \item Item 2
\end{enumerate}

An unordered list:

\begin{itemize}
  \item First bullet
  \item Second bullet
\end{itemize}

Now we have a blockquote:

\begin{quotation}
A big quote that goes on, and on, and on, and on, and on, and on, and on, and
on

A big quote that goes on, and on, and on, and on, and on, and on, and on, and
on

A big quote that goes on, and on, and on, and on, and on, and on, and on, and
on
\end{quotation}

Some mathematics inline, $X$, a \$100 million, a \%tage and then a formula:

\[ \sum_{i}^{\infty} x^{n} + y^{n} = \alpha +  \beta \cdot z^{n} \]

A paragraph with a\footnote{a very dull footnote indeed

but it does have mutiple paragraphs.} footnote in it\footnote{a very dull footnote indeed

but it does have mutiple paragraphs.}.

A table now (this is \emph{really} complicated):

\begin{table}
\begin{tabular}{|c|c|}
\hline
\textbf{Heading 1} & \textbf{Heading 2} \\
\hline
1.0\% & 2.0\% \\
\hline
1.0 & 2.0 \\
\hline
\end{tabular}
\\[5pt]
\caption{My Caption}
\end{table}

Now let's try having an image:

\begin{figure}
\centering
\includegraphics[width=\textwidth]{blah.png}
\caption{abc abc}
\end{figure}

Stuff we should escape A\&R, a \%tage sign

\begin{verbatim}
Now some preformatted text:

  \$ sudo python ...
\end{verbatim}
******** ACTUAL *********
<root>
\title{Anna Karenina}

% ----------------------------------------------------------------
\maketitle
% ----------------------------------------------------------------


\section{A first section}

A simple list:

\begin{enumerate}

  \item Item 1
  \item Item 2
\end{enumerate}

An unordered list:

\begin{itemize}
  \item First bullet
  \item Second bullet
\end{itemize}

Now we have a blockquote:

\begin{quotation}
A big quote that goes on, and on, and on, and on, and on, and on, and on, and
on

A big quote that goes on, and on, and on, and on, and on, and on, and on, and
on

A big quote that goes on, and on, and on, and on, and on, and on, and on, and
on
\end{quotation}

Some mathematics inline, \[X\], a \(100 million, a \%tage and then a formula:

\[ \sum_{i}^{\infty} x^{n} + y^{n} = \alpha +  \beta \cdot z^{n} \]

A paragraph with a[^fn1] footnote in it[^fn1].

[^fn1]: a very dull footnote indeed

\begin{verbatim}
but it does have mutiple paragraphs.
\end{verbatim}

A table now (this is \emph{really} complicated):

\begin{table}[h]
            \begin{tabular}{|l|l|}
            \hline
\textbf{Heading 1} \textbf{Heading 2} \\\hline
1.0\% 2.0\% \\
\hline
1.0 2.0 \\
            \hline
            \end{tabular}
            \\[5pt]
            \caption{My Caption}
            \end{table}


Now let's try having an image:

\begin{figure}[H]
            \centering
            \includegraphics[max width=\linewidth]{blah.png}
            \caption{abc abc}
            \end{figure}

Stuff we should escape A&R, a \%tage sign

\begin{verbatim}
Now some preformatted text:

  \) sudo python \dots
\end{verbatim}
</root>
******** ANALYSIS *********
0
out: "<root>"
exp: "\title{Anna Karenina}"
1
out: "\title{Anna Karenina}"
exp: ""
2
out: ""
exp: "% ----------------------------------------------------------------"
3
out: "% ----------------------------------------------------------------"
exp: "\maketitle"
4
out: "\maketitle"
exp: "% ----------------------------------------------------------------"
5
out: "% ----------------------------------------------------------------"
exp: ""
7
out: ""
exp: "\section{A first section}"
8
out: "\section{A first section}"
exp: ""
9
out: ""
exp: "A simple list:"
10
out: "A simple list:"
exp: ""
11
out: ""
exp: "\begin{enumerate}"
12
out: "\begin{enumerate}"
exp: "  \item Item 1"
13
out: ""
exp: "  \item Item 2"
14
out: "  \item Item 1"
exp: "\end{enumerate}"
15
out: "  \item Item 2"
exp: ""
16
out: "\end{enumerate}"
exp: "An unordered list:"
18
out: "An unordered list:"
exp: "\begin{itemize}"
19
out: ""
exp: "  \item First bullet"
20
out: "\begin{itemize}"
exp: "  \item Second bullet"
21
out: "  \item First bullet"
exp: "\end{itemize}"
22
out: "  \item Second bullet"
exp: ""
23
out: "\end{itemize}"
exp: "Now we have a blockquote:"
25
out: "Now we have a blockquote:"
exp: "\begin{quotation}"
26
out: ""
exp: "A big quote that goes on, and on, and on, and on, and on, and on, and on, and"
27
out: "\begin{quotation}"
exp: "on"
28
out: "A big quote that goes on, and on, and on, and on, and on, and on, and on, and"
exp: ""
29
out: "on"
exp: "A big quote that goes on, and on, and on, and on, and on, and on, and on, and"
30
out: ""
exp: "on"
31
out: "A big quote that goes on, and on, and on, and on, and on, and on, and on, and"
exp: ""
32
out: "on"
exp: "A big quote that goes on, and on, and on, and on, and on, and on, and on, and"
33
out: ""
exp: "on"
34
out: "A big quote that goes on, and on, and on, and on, and on, and on, and on, and"
exp: "\end{quotation}"
35
out: "on"
exp: ""
36
out: "\end{quotation}"
exp: "Some mathematics inline, $X$, a \$100 million, a \%tage and then a formula:"
38
out: "Some mathematics inline, \[X\], a \(100 million, a \%tage and then a formula:"
exp: "\[ \sum_{i}^{\infty} x^{n} + y^{n} = \alpha +  \beta \cdot z^{n} \]"
40
out: "\[ \sum_{i}^{\infty} x^{n} + y^{n} = \alpha +  \beta \cdot z^{n} \]"
exp: "A paragraph with a\footnote{a very dull footnote indeed"
42
out: "A paragraph with a[^fn1] footnote in it[^fn1]."
exp: "but it does have mutiple paragraphs.} footnote in it\footnote{a very dull footnote indeed"
44
out: "[^fn1]: a very dull footnote indeed"
exp: "but it does have mutiple paragraphs.}."
46
out: "\begin{verbatim}"
exp: "A table now (this is \emph{really} complicated):"
47
out: "but it does have mutiple paragraphs."
exp: ""
48
out: "\end{verbatim}"
exp: "\begin{table}"
49
out: ""
exp: "\begin{tabular}{|c|c|}"
50
out: "A table now (this is \emph{really} complicated):"
exp: "\hline"
51
out: ""
exp: "\textbf{Heading 1} & \textbf{Heading 2} \\"
52
out: "\begin{table}[h]"
exp: "\hline"
53
out: "            \begin{tabular}{|l|l|}"
exp: "1.0\% & 2.0\% \\"
54
out: "            \hline"
exp: "\hline"
55
out: "\textbf{Heading 1} \textbf{Heading 2} \\\hline"
exp: "1.0 & 2.0 \\"
56
out: "1.0\% 2.0\% \\"
exp: "\hline"
57
out: "\hline"
exp: "\end{tabular}"
58
out: "1.0 2.0 \\"
exp: "\\[5pt]"
59
out: "            \hline"
exp: "\caption{My Caption}"
60
out: "            \end{tabular}"
exp: "\end{table}"
61
out: "            \\[5pt]"
exp: ""
62
out: "            \caption{My Caption}"
exp: "Now let's try having an image:"
63
out: "            \end{table}"
exp: ""
64
out: ""
exp: "\begin{figure}"
65
out: ""
exp: "\centering"
66
out: "Now let's try having an image:"
exp: "\includegraphics[width=\textwidth]{blah.png}"
67
out: ""
exp: "\caption{abc abc}"
68
out: "\begin{figure}[H]"
exp: "\end{figure}"
69
out: "            \centering"
exp: ""
70
out: "            \includegraphics[max width=\linewidth]{blah.png}"
exp: "Stuff we should escape A\&R, a \%tage sign"
71
out: "            \caption{abc abc}"
exp: ""
72
out: "            \end{figure}"
exp: "\begin{verbatim}"
73
out: ""
exp: "Now some preformatted text:"
74
out: "Stuff we should escape A&R, a \%tage sign"
exp: ""
75
out: ""
exp: "  \$ sudo python ..."
76
out: "\begin{verbatim}"
exp: "\end{verbatim}"
Out longer than expected:
['Now some preformatted text:', '', '  \\) sudo python \\dots', '\\end{verbatim}', '</root>']
____________________________ TestTable2Latex.test_1 ____________________________

self = <mdx_latex_test.TestTable2Latex object at 0x102f23eb0>

    def test_1(self):
        converter = mdx_latex.Table2Latex()
>       out = converter.convert(self.intable1)

mdx_latex_test.py:236: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mdx_latex.py:379: in convert
    core = self.tolatex(dom.documentElement)
mdx_latex.py:356: in tolatex
    text = self.tolatex(child)
mdx_latex.py:356: in tolatex
    text = self.tolatex(child)
mdx_latex.py:356: in tolatex
    text = self.tolatex(child)
mdx_latex.py:370: in tolatex
    buffer = self.process_cell(element)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mdx_latex.Table2Latex object at 0x102f23bb0>
element = <DOM Element: td at 0x102fb04c0>

    def process_cell(self, element):
        # works on both td and th
        colspan = 1
        subcontent = self.get_text(element)
        buffer = ""
    
        if element.tagName == 'th':
            subcontent = '\\textbf{%s}' % subcontent
        if element.hasAttribute('colspan'):
            colspan = int(element.getAttribute('colspan'))
            buffer += ' \multicolumn{%s}{|c|}{%s}' % (colspan, subcontent)
        # we don't support rowspan because:
        #   1. it needs an extra latex package \usepackage{multirow}
        #   2. it requires us to mess around with the alignment tags in
        #   subsequent rows (i.e. suppose the first col in row A is rowspan 2
        #   then in row B in the latex we will need a leading &)
        # if element.hasAttribute('rowspan'):
        #     rowspan = int(element.getAttribute('rowspan'))
        #     buffer += ' \multirow{%s}{|c|}{%s}' % (rowspan, subcontent)
        else:
            buffer += ' %s' % subcontent
    
>       notLast = (element.nextSibling.nextSibling and
                   element.nextSibling.nextSibling.nodeType ==
                   element.ELEMENT_NODE and
                   element.nextSibling.nextSibling.tagName in ['td', 'th'])
E       AttributeError: 'NoneType' object has no attribute 'nextSibling'

mdx_latex.py:337: AttributeError
____________________________ TestMathConvert.test_1 ____________________________

self = <mdx_latex_test.TestMathConvert object at 0x102ef2590>

    def test_1(self):
        converter = mdx_latex.MathTextPostProcessor()
        out = converter.run(self.intext)
        print(out)
>       assert out == self.outtext
E       AssertionError: assert '\n\\[ \\sum_...array}\n\\]\n' == '\n\\[ \\sum_...array}\n\\]\n'
E           
E           \[ \sum_{x=1} ... \]
E           
E         - Hello world, $x$. \$100 million.
E         ?              ^ ^  -
E         + Hello world, \[x\]. $100 million.
E         ?              ^^ ^^...
E         
E         ...Full output truncated (13 lines hidden), use '-vv' to show

mdx_latex_test.py:278: AssertionError
----------------------------- Captured stdout call -----------------------------

\[ \sum_{x=1} ... \]

Hello world, \[x\]. $100 million.

\[x=5\], but then along comes the fox! \[y=6\]

\[
egin{eqnarray}
W & = & y + z \\
  & = & 3x
\end{eqnarray}
\]

____________________________ TestImgConvert.test_1 _____________________________

self = <mdx_latex_test.TestImgConvert object at 0x102f23430>

    def test_1(self):
        converter = mdx_latex.Img2Latex()
        out = converter.convert(self.intext)
        print(out)
>       assert out == self.exp1
E       AssertionError: assert '\n          ...n            ' == '\n\\begin{fi...end{figure}\n'
E           
E         - \begin{figure}
E         - \centering
E         +             \begin{figure}[H]
E         +             \centering
E         - \includegraphics[width=\textwidth]{blah.png}
E         ?                         ^ --...
E         
E         ...Full output truncated (9 lines hidden), use '-vv' to show

mdx_latex_test.py:298: AssertionError
----------------------------- Captured stdout call -----------------------------

            \begin{figure}[H]
            \centering
            \includegraphics[max width=\linewidth]{blah.png}
            \caption{abc abc}
            \end{figure}
            
=============================== warnings summary ===============================
<unknown>:72
<unknown>:72
<unknown>:72
<unknown>:72
<unknown>:72
  <unknown>:72: DeprecationWarning: invalid escape sequence '\m'

<unknown>:186
<unknown>:186
<unknown>:186
<unknown>:186
<unknown>:186
  <unknown>:186: DeprecationWarning: invalid escape sequence '\#'

<unknown>:218
<unknown>:218
<unknown>:218
<unknown>:218
<unknown>:218
  <unknown>:218: DeprecationWarning: invalid escape sequence '\h'

<unknown>:244
<unknown>:244
<unknown>:244
<unknown>:244
<unknown>:244
  <unknown>:244: DeprecationWarning: invalid escape sequence '\e'

<unknown>:259
<unknown>:259
<unknown>:259
<unknown>:259
<unknown>:259
  <unknown>:259: DeprecationWarning: invalid escape sequence '\$'

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED mdx_latex_test.py::TestMkdn2Latex::test_1 - AssertionError: assert '<r...
FAILED mdx_latex_test.py::TestTable2Latex::test_1 - AttributeError: 'NoneType...
FAILED mdx_latex_test.py::TestMathConvert::test_1 - AssertionError: assert '\...
FAILED mdx_latex_test.py::TestImgConvert::test_1 - AssertionError: assert '\n...
=================== 4 failed, 1 passed, 25 warnings in 0.12s ===================
```

**Comment by rufuspollock** [comment]
OK, i'm going to merge this for now as it will address (i suspect) #20.

Would be nice if someone fixes the test.

@JJK96 thanks for the submission.

**Pull request merged**
